[tool.poetry]
name = "zkCreditScore"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
ezkl = "^4.2.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
